// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTjPJ7mt7VUkOeSyzV355nHHKuSgg2fQ',
    appId: '1:656567245169:web:47373aece29777ba31bed0',
    messagingSenderId: '656567245169',
    projectId: 'gamelovers-e2abd',
    authDomain: 'gamelovers-e2abd.firebaseapp.com',
    storageBucket: 'gamelovers-e2abd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNAe6pFsUlRg8HC4pr5nSpPrTed9vM60',
    appId: '1:656567245169:android:7ee2530af0fdd30131bed0',
    messagingSenderId: '656567245169',
    projectId: 'gamelovers-e2abd',
    storageBucket: 'gamelovers-e2abd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUw-PSU5qy1JoJz7Vb-yd7qF04ZTGqQUY',
    appId: '1:656567245169:ios:3395b3d884c32d3631bed0',
    messagingSenderId: '656567245169',
    projectId: 'gamelovers-e2abd',
    storageBucket: 'gamelovers-e2abd.appspot.com',
    iosBundleId: 'com.example.gamelovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUw-PSU5qy1JoJz7Vb-yd7qF04ZTGqQUY',
    appId: '1:656567245169:ios:3395b3d884c32d3631bed0',
    messagingSenderId: '656567245169',
    projectId: 'gamelovers-e2abd',
    storageBucket: 'gamelovers-e2abd.appspot.com',
    iosBundleId: 'com.example.gamelovers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTjPJ7mt7VUkOeSyzV355nHHKuSgg2fQ',
    appId: '1:656567245169:web:5c8d255d7fd64f6331bed0',
    messagingSenderId: '656567245169',
    projectId: 'gamelovers-e2abd',
    authDomain: 'gamelovers-e2abd.firebaseapp.com',
    storageBucket: 'gamelovers-e2abd.appspot.com',
  );
}
